"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING

from magicgui.widgets import Container, RadioButtons, create_widget
from napari.layers import Surface

if TYPE_CHECKING:
    import napari


# if we want even more control over our widget, we can use
# magicgui `Container`
class SurfaceChannelChange(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        self._channels: list[str] = []
        # use create_widget to generate widgets from type annotations
        self._surface_layer_combo = create_widget(
            label="Surface", annotation="napari.layers.Surface"
        )
        # Selection widget
        self._channel_selector = RadioButtons()
        self._surface_layer_combo.changed.connect(self._on_change_surface)
        self._channel_selector.changed.connect(self._on_change_channel)
        self._viewer.layers.events.connect(self._on_layers_changed)
        # append into/extend the container with your widgets
        self.extend(
            [
                self._surface_layer_combo,
                self._channel_selector,
            ]
        )
        if len(viewer.layers) > 0:
            self._on_layers_changed(None)
            self._on_change_surface(self._surface_layer_combo.value)

    def _on_layers_changed(self, event):
        self._surface_layer_combo.choices = [
            x for x in self._viewer.layers if type(x) is Surface
        ]

    def _on_change_surface(self, surface_layer):
        self._channels = []
        if surface_layer is not None:
            n_points = surface_layer.vertices.shape[0]
            if surface_layer.features.shape[0] == n_points:
                self._channels = list(surface_layer.features.columns)
        self._channel_selector.choices = self._channels

    def _on_change_channel(self, channel_name):
        surface_layer = self._surface_layer_combo.value
        if surface_layer is None or len(self._channels) == 0:
            return

        surface_layer.vertex_values = surface_layer.features[channel_name]
